name: Fly Deploy
on:
  push:
    branches:
      - master    # change to main if needed
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Notify Discord on new deployment
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          description: to <https://full-stack-open-pokedex-tetuanka.fly.dev/> by ${{ github.actor }}
          text: A new version of Pokedex deployed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ', '), 'skip')}}