name: Health check

#on:
#  schedule:
#    - cron:  '30 12 * * *'


jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          # Check the following URL
          url: https://full-stack-open-pokedex-tetuanka.fly.dev/
 
